#взял отсюда https://gist.github.com/ruanbekker/c6fa9bc6882e6f324b4319c5e3622460


server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
 # - url: http://192.168.4.68:3100/loki/api/v1/push
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
      
- job_name: containers
  static_configs:
  - targets:
      - localhost
    labels:
      job: containerlogs
      __path__: /var/lib/docker/containers/*/*log

  pipeline_stages:
    - regex:
        expression: '^(?P<container_name>[^|]+)\|(?P<image_name>.+)$'  # Извлекаем имя контейнера и имя образа из тега
        source: "tag"
    - labels:
        container_name: '{{ .container_name }}'  # Добавляем метку container_name
        image_name: '{{ .image_name }}'          # Добавляем метку image_name
