groups:
  - name: containers_alerts
    rules:
      - alert: OneOfTheContainersFell
        expr: up == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "{{ $labels.job }} is down on {{ $labels.instance }}"
          description: "{{ $labels.job }} has been down for more than 1 minute on {{ $labels.instance }}."